spring.application.name=EShop
spring.datasource.url=jdbc:postgresql://localhost:5432/eshop_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true